version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - VITE_NODE_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_NODE_ENV=development
    depends_on:
      - server

volumes:
  client_node_modules:
  server_node_modules:
